services:
  - type: web
    name: swimtrack-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: ./render_start.sh
    envVars:
      - key: SWIMTRACK_DB_PATH
        value: /tmp/swimtrack.db
